# Generated by Django 3.0.6 on 2020-06-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='title',
            field=models.TextField(default='', verbose_name='Tytuł formuły'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='text',
            field=models.TextField(verbose_name='Formuła matematyczna w języku Latex'),
        ),
    ]
