# Generated by Django 3.0.6 on 2020-06-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0003_formula_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='text',
            field=models.TextField(verbose_name='Wyrażenie matematyczna w języku Latex'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='title',
            field=models.TextField(default='', verbose_name='Tytuł wyrażenia'),
        ),
    ]
